[versions]
agp = "7.4.2"
kotlin = "1.8.10"
kotlinxCoroutines = "1.6.4"
kotlinxSerialization = "1.5.0"

androidxComposeCompiler = "1.4.3"
androidxComposeMaterial = "1.4.0-rc01"
androidxComposeMaterial3 = "1.1.0-alpha08"
androidxComposeUi = "1.4.0-rc01"
androidxDataStore = "1.0.0"
androidxHilt = "1.0.0"
androidxLifecycle = "2.6.0"
androidxNavigation = "2.5.3"
androidxRoom = "2.5.0"
androidxSplashScreen = "1.0.0"
androidxStartup = "1.1.1"
androidxWindow = "1.1.0-alpha06"
androidxWork = "2.8.0"

coil = "2.2.2"
desugarJdkLibs = "2.0.2"
detekt = "1.22.0"
dbtools = "8.0.0"

firebaseBom = "31.2.3"
firebaseAppDistGradlePlugin = "4.0.0"
firebaseCrashlyticsGradlePlugin = "2.9.4"
firebasePerfGradlePlugin = "1.4.2"

googlePlayCore = "1.8.1"
googleServicesGradlePlugin = "4.3.15"

hilt = "2.45"
junit = "5.9.2"
ksp = "1.8.10-1.0.9"
leakCanary = "2.10"
licenseManagerGradlePlugin = "1.1.0"
mockK = "1.13.4"
okhttp = "4.10.0"
playPublisher = "3.8.1"
retrofit = "2.9.0"
ruler = "1.4.0"
sqliteJdbc = "3.41.0.0"
timber = "5.0.1"
truth = "1.1.3"
versionsGradlePlugin = "0.46.0"
workManagerTools = "3.0.0"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
#playPublisher = { id = "com.github.triplet.play", version.ref = "playPublisher" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-desugar = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugarJdkLibs" }

androidx-datastorePrefs = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDataStore" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup" }

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxHilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxHilt" }

androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidxRoom" }

androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplashScreen" }

androidx-window = { module = "androidx.window:window", version.ref = "androidxWindow" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWork" }
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "androidxWork" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidxComposeMaterial" } # Material design icons (extended)
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidxComposeMaterial3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidxComposeUi" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidxComposeUi" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidxComposeUi" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidxComposeUi" } # Tooling support (Previews, etc.)
compose-material3-windowsize = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "androidxComposeMaterial3" }

dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "hilt" }

dbtools-licenseManager-gradlePluginClasspath = { module = "org.dbtools:license-manager-gradle-plugin", version.ref = "licenseManagerGradlePlugin" }

dbtools-room = { module = "org.dbtools:dbtools-room", version.ref = "dbtools" }
dbtools-roomSqlite = { module = "org.dbtools:dbtools-room-sqliteorg", version.ref = "dbtools" }
dbtools-roomJdbc = { module = "org.dbtools:dbtools-room-jdbc", version.ref = "dbtools" }
dbtools-roomJdbcTest = { module = "org.dbtools:dbtools-room-jdbc-test", version.ref = "dbtools" }

google-servicesgradlePluginClasspath = { module = "com.google.gms:google-services", version.ref = "googleServicesGradlePlugin" }

# Firebase - https://firebase.google.com/support/release-notes/android
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-firebase-appDistGradlePluginClasspath = { module = "com.google.firebase:firebase-appdistribution-gradle", version.ref = "firebaseAppDistGradlePlugin" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-config = { module = "com.google.firebase:firebase-config-ktx" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-crashlyticsGradlePluginClasspath = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradlePlugin" }
google-firebase-perf = { module = "com.google.firebase:firebase-perf" }
google-firebase-perfGradlePluginClasspath = { module = "com.google.firebase:perf-plugin", version.ref = "firebasePerfGradlePlugin" }

google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
google-hilt-gradlePluginClasspath = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
google-hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

google-play-core = { module = "com.google.android.play:core-ktx", version.ref = "googlePlayCore" } # https://developer.android.com/reference/com/google/android/play/core/release-notes

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlin-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver" }

mockK = { module = "io.mockk:mockk", version.ref = "mockK" }

playPublisherGradlePluginClasspath = { module = "com.github.triplet.gradle:play-publisher", version.ref = "playPublisher" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

ruler-gradlePluginClasspath = { module = "com.spotify.ruler:ruler-gradle-plugin", version.ref = "ruler" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

truth = { module = "com.google.truth:truth", version.ref = "truth" }

gradleVersions-gradlePluginClasspath = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsGradlePlugin" }

workmanagertools = { module = "org.dbtools:workmanager-tools", version.ref = "workManagerTools" }

xerial-sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }
