[versions]
agp = "7.1.3"
kotlin = "1.6.20"
coroutines = "1.6.1"

accompanist = "0.24.1-alpha"
androidxhilt = "1.0.0"
androidxlifecycle = "2.4.1"
coil = "1.4.0"
compose = "1.2.0-alpha08"
dagger = "2.41"
dbtools = "7.0.1"
hilt = "2.41"
ktlint = "0.40.0"
navigation = "2.4.2"
paging = "3.0.0-beta02"
retrofit = "2.9.0"
room = "2.4.2"
work = "2.7.1"

[plugins]
ksp = { id = "com.google.devtools.ksp", version = "1.6.20-1.0.5" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.20.0" }
playPublisher = { id = "com.github.triplet.play", version = "3.7.0" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }

android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }

androidx-activity = { module = "androidx.activity:activity-ktx", version = "1.4.0" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.4.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.1" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.3" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.7.0-beta02" }
androidx-datastorePrefs = { module = "androidx.datastore:datastore-preferences", version = "1.0.0" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version = "1.4.1" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.2.1" }
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.1.1" }

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }

androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidxlifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxlifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxlifecycle" }


#androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "paging" }
#androidx-paging-compose = { module = "androidx.paging:paging-compose", version = "1.0.0-alpha12" }
#androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0-beta02" }

androidx-window = { module = "androidx.window:window", version = "1.0.0" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "work" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" } # Material design icons (extended)
compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" } # Material Design
compose-material-material3 = { module = "androidx.compose.material3:material3", version = "1.0.0-alpha01" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" } # Tooling support (Previews, etc.)

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

dbtools-licenseManager-gradlePluginClasspath = { module = "org.dbtools:license-manager-gradle-plugin", version = "1.1.0" }

dbtools-room = { module = "org.dbtools:dbtools-room", version.ref = "dbtools" }
dbtools-roomSqlite = { module = "org.dbtools:dbtools-room-sqliteorg", version.ref = "dbtools" }
dbtools-roomJdbcTest = { module = "org.dbtools:dbtools-room-jdbc-test", version.ref = "dbtools" }

#dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.4.30" }

google-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version = "18.0.2" }
google-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version = "17.4.0" }
google-crashlyticsGradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "2.5.1" }

google-material = { module = "com.google.android.material:material", version = "1.5.0" } # https://github.com/material-components/material-components-android/releases
google-servicesgradlePluginClasspath = { module = "com.google.gms:google-services", version = "4.3.10" } # NOTE 4.3.9 is NOT compatible with firebase-bom 28.3.1

# Firebase - https://firebase.google.com/support/release-notes/android
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version = "29.3.1" }
google-firebase-appDistGradlePluginClasspath = { module = "com.google.firebase:firebase-appdistribution-gradle", version = "3.0.1" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-config = { module = "com.google.firebase:firebase-config-ktx" }
google-firebase-core = { module = "com.google.firebase:firebase-core" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-crashlyticsGradlePluginClasspath = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "2.8.1" }
google-firebase-perf = { module = "com.google.firebase:firebase-perf" }
google-firebase-perfGradlePluginClasspath = { module = "com.google.firebase:perf-plugin", version = "1.3.4" }

google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
google-hilt-gradlePluginClasspath = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
google-hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

google-play-core = { module = "com.google.android.play:core-ktx", version = "1.8.1" } # https://developer.android.com/reference/com/google/android/play/core/release-notes

junit-bom = { module = "org.junit:junit-bom", version = "5.8.2" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

kotlin-binaryCompatibility = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version = "0.3.0" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.2" }

leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.9.1" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version = "4.9.3" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver" }

mockK = { module = "io.mockk:mockk", version = "1.12.3" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

ruler-gradlePluginClasspath = { module = "com.spotify.ruler:ruler-gradle-plugin", version = "1.2.0" }

timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

truth = { module = "com.google.truth:truth", version = "1.1.3" }

gradleVersions-gradlePluginClasspath = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.42.0" }

workmanagertools = { module = "org.dbtools:workmanager-tools", version = "2.0.0" }

xerial-sqlite = { module = "org.xerial:sqlite-jdbc", version = "3.36.0.3" }
