[versions]
agp = "8.8.1"
kotlin = "2.1.10"
kotlinxCoroutines = "1.10.1"
kotlinxSerialization = "1.8.0"
kotlinxDateTime = "0.6.2"

androidxActivity = "1.10.0"
androidxComposeMaterial = "1.7.8"
androidxComposeMaterial3 = "1.3.1"
androidxComposeMaterial3Adaptive = "1.0.0"
androidxComposeMaterial3AdaptiveNavigation = "1.3.1"
androidxComposeUi = "1.7.8"
androidxDataStore = "1.1.2"
androidxHilt = "1.2.0"
androidxLifecycle = "2.8.7"
androidxNavigation = "2.8.7"
androidxPagingCompose = "3.3.6"
androidxRoom = "2.6.1"
androidxSplashScreen = "1.1.0-rc01"
androidxStartup = "1.2.0"
androidxWindow = "1.3.0"
androidxWork = "2.10.0"

assertk = "0.28.1"
coil = "2.7.0"
dependencyAnalysis = "2.10.1"
desugarJdkLibs = "2.1.5"
detekt = "1.23.8"
dbtools = "8.3.0"
downloadPlugin = "5.6.0"

firebaseBom = "33.9.0"
firebaseAppDistPlugin = "5.1.1"
firebaseCrashlyticsPlugin = "3.0.3"
firebasePerfPlugin = "1.4.2"

gmsPlugin = "4.4.2"

hilt = "2.55"
kermit = "2.0.5"
konsist = "0.17.3"
kover = "0.9.1"
ksp = "2.1.10-1.0.29"
ktor = "3.1.0"
leakCanary = "2.14"
licenseManager = "1.4.0"
mockK = "1.13.16"
okio = "3.10.2"
playPublisher = "3.12.1"
ruler = "1.4.0"
sqliteJdbc = "3.49.0.0"
turbine = "1.2.0"
versionsPlugin = "0.52.0"
workManagerTools = "4.0.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
download = { id = "de.undercouch.download", version.ref = "downloadPlugin" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppDistPlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
licenseManager = { id = "org.dbtools.license-manager", version.ref = "licenseManager" }
playPublisher = { id = "com.github.triplet.play", version.ref = "playPublisher" }
room = { id = "androidx.room", version.ref = "androidxRoom" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }

[libraries]
android-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-datastorePrefs = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidxStartup" }

androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHilt" }

androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPagingCompose" }

androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidxRoom" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "androidxRoom" }

androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashScreen" }

androidx-window = { group = "androidx.window", name = "window", version.ref = "androidxWindow" }

androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
androidx-work-gcm = { group = "androidx.work", name = "work-gcm", version.ref = "androidxWork" }

assertk = { group = "com.willowtreeapps.assertk", name = "assertk", version.ref = "assertk" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

compose-material-iconsext = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidxComposeMaterial" } # Material design icons (extended)
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "androidxComposeMaterial3Adaptive" }
compose-material3-adaptive-navigation = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "androidxComposeMaterial3AdaptiveNavigation" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxComposeUi" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidxComposeUi" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidxComposeUi" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxComposeUi" } # Tooling support (Previews, etc.)
compose-material3-windowsize = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidxComposeMaterial3" }

dbtools-room = { group = "org.dbtools", name = "dbtools-room", version.ref = "dbtools" }
dbtools-roomSqlite = { group = "org.dbtools", name = "dbtools-room-sqliteorg", version.ref = "dbtools" }
dbtools-roomJdbc = { group = "org.dbtools", name = "dbtools-room-jdbc", version.ref = "dbtools" }
dbtools-roomJdbcTest = { group = "org.dbtools", name = "dbtools-room-jdbc-test", version.ref = "dbtools" }

# Firebase - https://firebase.google.com/support/release-notes/android
google-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
google-firebase-config = { group = "com.google.firebase", name = "firebase-config" }
google-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

google-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
google-hilt-library = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
google-hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }

kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
kermit-crashlytics = { group = "co.touchlab", name = "kermit-crashlytics", version.ref = "kermit" }

konsist = { group = "com.lemonappdev", name = "konsist", version.ref = "konsist" }

kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlin-coroutines-playServices = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutines" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDateTime" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-resources = { group = "io.ktor", name = "ktor-client-resources", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

leakCanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" }

okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }

mockK = { group = "io.mockk", name = "mockk", version.ref = "mockK" }

ruler-gradlePluginClasspath = { group = "com.spotify.ruler", name = "ruler-gradle-plugin", version.ref = "ruler" }

turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

workmanagertools = { group = "org.dbtools", name = "workmanager-tools", version.ref = "workManagerTools" }

xerial-sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqliteJdbc" }
